<x-layouts.admin title="Archived V2 Tournaments">
    <div class="mx-auto max-w-7xl space-y-5">
        <div><a href="{{ route('admin.tournaments') }}" class="text-xs font-bold text-indigo-400">← Tournaments</a><h1 class="mt-2 text-2xl font-black text-white">Archived V2 tournaments</h1><p class="mt-1 text-sm text-slate-400">Archived records are hidden from normal lists; registrations, matches, payouts and ledger history remain stored.</p></div>
        @if(session('success'))<div class="rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-300">{{ session('success') }}</div>@endif
        <div class="overflow-hidden rounded-xl border border-slate-800 bg-[#0f172a]"><div class="overflow-x-auto"><table class="w-full text-left text-xs"><thead><tr class="border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400"><th class="p-4">Tournament</th><th class="p-4">Game</th><th class="p-4">Status</th><th class="p-4">Start (UTC)</th><th class="p-4">Archived at</th><th class="p-4 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-800/60">
            @forelse($tournaments as $tournament)<tr><td class="p-4 font-semibold text-slate-100">{{ $tournament->name }}</td><td class="p-4 text-slate-300">{{ $tournament->game?->translations->first()?->name ?? $tournament->game?->slug ?? '—' }}</td><td class="p-4 text-slate-300">{{ str_replace('_', ' ', $tournament->status->value) }}</td><td class="p-4 tabular-nums text-slate-300">{{ $tournament->start_at?->utc()->format('Y-m-d H:i:s') ?? '—' }}</td><td class="p-4 tabular-nums text-slate-400">{{ $tournament->deleted_at?->utc()->format('Y-m-d H:i:s') }}</td><td class="p-4 text-right">@can('tournaments.manage')<form method="POST" action="{{ route('admin.tournaments.v2.archived.restore', $tournament->id) }}" onsubmit="return confirm('Restore this tournament to normal lists?')">@csrf<button class="rounded-lg border border-slate-700 px-3 py-2 text-[10px] font-bold uppercase text-slate-300 hover:bg-slate-800">Restore</button></form>@endcan</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No archived V2 tournaments.</td></tr>@endforelse
        </tbody></table></div>@if($tournaments->hasPages())<div class="border-t border-slate-800 px-4 py-3">{{ $tournaments->links('vendor.livewire.custom-pagination') }}</div>@endif</div>
    </div>
</x-layouts.admin>
