<x-layouts.admin :admin-title="'Add Tournament Slot'">
    @php $frequency = $template->recurrence_frequency?->value ?? 'one_time'; @endphp
    <div class="mx-auto max-w-3xl">
        <header class="mb-6"><a href="{{ route('admin.tournaments.v2.templates.slots', $template) }}" class="text-xs font-semibold text-indigo-300 hover:text-white">← Back to slots</a><p class="mt-4 text-[10px] font-black uppercase tracking-[.24em] text-indigo-400">{{ $template->name }}</p><h1 class="mt-1 text-2xl font-black text-white">Add schedule slot</h1><p class="mt-2 text-sm text-slate-400">This only creates a new slot. It inherits the parent defaults unless you set one of the optional overrides below.</p></header>
        @if($errors->any())<div class="mb-5 rounded-xl border border-red-800/70 bg-red-950/30 p-4 text-sm text-red-200"><ul class="list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ route('admin.tournaments.v2.templates.slots.store', $template) }}" class="space-y-5">@csrf
            <section class="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><h2 class="text-xs font-black uppercase tracking-wider text-slate-200">Slot schedule</h2><div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label class="slot-label">Label</label><input name="label" value="{{ old('label') }}" placeholder="e.g. Evening" class="slot-field"></div><div><label class="slot-label">Frequency</label><input value="{{ str_replace('_', '-', $frequency) }}" disabled class="slot-field opacity-60"></div><div><label class="slot-label">Start date and time</label><input name="schedule_start_at" type="datetime-local" min="{{ $now->format('Y-m-d\TH:i') }}" value="{{ old('schedule_start_at', $now->format('Y-m-d\TH:i')) }}" class="slot-field" required></div><div><label class="slot-label">End date and time</label><input name="schedule_end_at" type="datetime-local" min="{{ $now->format('Y-m-d\TH:i') }}" value="{{ old('schedule_end_at', $now->endOfDay()->format('Y-m-d\TH:i')) }}" class="slot-field" required></div>
                @if($frequency === 'weekly')<div><label class="slot-label">Day of week</label><select name="day_of_week" class="slot-field" required>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as $index => $day)<option value="{{ $index }}" @selected((string) old('day_of_week', $now->dayOfWeekIso - 1) === (string) $index)>{{ $day }}</option>@endforeach</select></div>@endif
                @if($frequency === 'monthly')<div><label class="slot-label">Day of month</label><input name="day_of_month" type="number" min="1" max="31" value="{{ old('day_of_month', $now->day) }}" class="slot-field" required></div>@endif
            </div><p class="mt-4 text-xs leading-relaxed text-slate-500">Timezone: {{ $template->timezone }}. Previous dates are blocked. A recurring slot whose time already passed today waits for its next valid recurrence.</p></section>
            <section class="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><h2 class="text-xs font-black uppercase tracking-wider text-slate-200">Optional slot overrides</h2><p class="mt-2 text-xs text-slate-500">Leave blank to use the parent values: {{ $template->name }}, {{ $template->max_participants }} teams, ${{ number_format((float) $template->entry_fee, 2) }} entry fee.</p><div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label class="slot-label">Tournament name</label><input name="name" value="{{ old('name') }}" placeholder="Use parent name" class="slot-field"></div><div><label class="slot-label">Maximum teams</label><input name="max_teams" type="number" min="2" max="128" step="2" value="{{ old('max_teams') }}" placeholder="Use {{ $template->max_participants }}" class="slot-field"><p class="mt-1 text-[11px] text-slate-500">Only even numbers, 2–128.</p></div><div><label class="slot-label">Entry fee</label><input name="entry_fee" inputmode="decimal" value="{{ old('entry_fee') }}" placeholder="Use ${{ number_format((float) $template->entry_fee, 2) }}" class="slot-field"></div></div></section>
            <footer class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('admin.tournaments.v2.templates.slots', $template) }}" class="slot-cancel">Cancel</a><button class="slot-submit">Add slot</button></footer>
        </form>
    </div>
    <style>.slot-label{display:block;margin-bottom:.4rem;color:#94a3b8;font-size:.6875rem;font-weight:700;text-transform:uppercase}.slot-field{width:100%;border:1px solid #334155;border-radius:.625rem;background:#020617;padding:.625rem .75rem;color:#f8fafc;font-size:.8125rem;outline:none}.slot-field:focus{border-color:#6366f1;box-shadow:0 0 0 3px rgba(99,102,241,.12)}.slot-submit,.slot-cancel{display:inline-flex;justify-content:center;border-radius:.625rem;padding:.65rem 1rem;font-size:.75rem;font-weight:800}.slot-submit{background:#4f46e5;color:#fff}.slot-cancel{border:1px solid #334155;color:#cbd5e1}</style>
</x-layouts.admin>
