<x-layouts.admin title="Edit Tournament V2">
    <div class="mx-auto max-w-3xl"><div class="mb-6"><a href="{{ route('admin.tournaments') }}" class="text-xs font-bold text-indigo-400">← Tournaments</a><h1 class="mt-2 text-2xl font-black text-white">Edit V2 Occurrence</h1><p class="mt-1 text-xs text-slate-400">Game is fixed. @if($hasRegistrations)A player has joined, so only presentation fields remain editable.@else Structural settings lock after the first player joins.@endif</p></div>
    @if($errors->any())<div class="mb-4 rounded-lg border border-red-800 bg-red-950/30 p-3 text-xs text-red-300">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('admin.tournaments.v2.occurrences.update', $tournament) }}" enctype="multipart/form-data" class="space-y-4 rounded-xl border border-slate-800 bg-slate-900/70 p-6">@csrf @method('PUT')
        <div class="rounded-lg border border-slate-800 bg-slate-950 p-3 text-xs text-slate-400">Game: <strong class="text-white">{{ $tournament->game->localizedName() }}</strong> · Minimum Participants: 2 · Team Size: 1 · Play XP: 10</div>
        <label class="flex cursor-pointer items-start gap-3 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><input name="is_featured" value="1" type="checkbox" @checked(old('is_featured', $tournament->is_featured)) class="mt-0.5 rounded border-slate-700 bg-slate-900 text-amber-500"><span><span class="block text-xs font-black uppercase text-amber-300">Featured Tournament</span><span class="mt-1 block text-xs leading-relaxed text-slate-500">Display this tournament in featured tournament galleries.</span></span></label>
        @unless($hasRegistrations)<div class="grid gap-4 md:grid-cols-2"><label class="text-xs text-slate-400 md:col-span-2">Name<input name="name" value="{{ old('name', $tournament->name) }}" class="mt-1 w-full rounded-lg border-slate-700 bg-slate-950 text-white"></label><label class="text-xs text-slate-400">Maximum Teams<select name="max_teams" class="mt-1 w-full rounded-lg border-slate-700 bg-slate-950 text-white">@foreach([4,8,16,32,64] as $size)<option @selected($tournament->max_participants === $size)>{{ $size }}</option>@endforeach</select></label><label class="text-xs text-slate-400">Entry Fee<input name="entry_fee" value="{{ old('entry_fee', $tournament->entry_fee) }}" class="mt-1 w-full rounded-lg border-slate-700 bg-slate-950 text-white"></label><fieldset><legend class="text-xs text-slate-400">{{ __('Platforms') }}</legend><input type="hidden" name="platform_ids" value=""><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($tournament->game->platforms as $platform)<label class="flex items-center gap-2 text-sm text-slate-200"><input type="checkbox" name="platform_ids[]" value="{{ $platform->id }}" @checked(in_array($platform->id, (array) old('platform_ids', $tournament->supportedPlatformIds())))>{{ $platform->name }}</label>@endforeach</div>@error('platform_ids')<p class="text-xs text-red-400">{{ $message }}</p>@enderror @error('platform_ids.*')<p class="text-xs text-red-400">{{ $message }}</p>@enderror</fieldset><label class="text-xs text-slate-400">Winning Points (XP)<input name="winning_points" type="number" min="0" value="{{ old('winning_points', $tournament->winning_points) }}" class="mt-1 w-full rounded-lg border-slate-700 bg-slate-950 text-white"></label><label class="text-xs text-slate-400">Start Date and Time<input name="start_at" type="datetime-local" value="{{ old('start_at', $tournament->start_at?->setTimezone($tournament->timezone)->format('Y-m-d\TH:i')) }}" min="{{ now($tournament->timezone)->format('Y-m-d\TH:i') }}" class="mt-1 w-full rounded-lg border-slate-700 bg-slate-950 text-white"></label><label class="text-xs text-slate-400">End Date<input name="end_date" type="date" value="{{ old('end_date', $tournament->end_at?->setTimezone($tournament->timezone)->subDay()->format('Y-m-d')) }}" min="{{ now($tournament->timezone)->format('Y-m-d') }}" class="mt-1 w-full rounded-lg border-slate-700 bg-slate-950 text-white"><span class="mt-1 block text-[10px] text-slate-500">The occurrence closes at midnight after this date.</span></label><label class="text-xs text-slate-400">Result response minutes<input name="waiting_result_time" type="number" min="1" value="{{ old('waiting_result_time', $tournament->waiting_result_time) }}" class="mt-1 w-full rounded-lg border-slate-700 bg-slate-950 text-white"></label></div>@endunless
        <x-forms.controller-image-crop-upload name="banner" label="Tournament banner" :width="960" :height="540" :current-url="$tournament->banner_url" help="Leave blank to retain the existing tournament banner. New uploads are cropped before saving." />
        <x-forms.quill-editor name="description" label="Description" :value="old('description', $tournament->description)" placeholder="Explain the tournament format and what players can expect." />
        <x-forms.quill-editor name="rules" label="Tournament rules" :value="old('rules', $tournament->rules)" placeholder="Add rules specific to this tournament." height="h-64" />
        <button class="rounded-lg bg-indigo-600 px-5 py-2.5 text-xs font-black text-white">Save Occurrence</button>
    </form></div>
    <style>
        form label>input:not([type=checkbox]),form label>select{padding:.6rem .75rem;font-size:.8125rem;line-height:1.1}.v2-field-label{display:block;margin-bottom:.4rem;color:rgb(148 163 184);font-size:.6875rem;font-weight:700;letter-spacing:.025em;text-transform:uppercase}.v2-field-error{margin-top:.3rem;color:rgb(248 113 113);font-size:.6875rem}.ql-toolbar.ql-snow,.ql-container.ql-snow{border-color:rgb(30 41 59)!important}.ql-toolbar.ql-snow{background:rgb(2 6 23);border-radius:.75rem .75rem 0 0;flex-wrap:wrap}.ql-container.ql-snow{border-radius:0 0 .75rem .75rem}.ql-snow .ql-stroke{stroke:rgb(148 163 184)!important}.ql-snow .ql-fill{fill:rgb(148 163 184)!important}.ql-snow .ql-picker,.ql-snow .ql-picker-label{color:rgb(148 163 184)!important}.ql-snow .ql-picker-options,.ql-snow .ql-tooltip{background:rgb(15 23 42)!important;border-color:rgb(30 41 59)!important;color:rgb(226 232 240)!important}.ql-snow .ql-picker-item{color:rgb(148 163 184)!important}.ql-snow button:hover .ql-stroke,.ql-snow button.ql-active .ql-stroke{stroke:#fff!important}.ql-snow button:hover .ql-fill,.ql-snow button.ql-active .ql-fill{fill:#fff!important}.ql-editor-shell{height:14rem;overflow:hidden}.ql-editor-shell .ql-container{height:calc(100% - 42px);overflow:hidden}.ql-editor-shell .ql-editor{height:100%;min-height:0;overflow-y:auto;color:rgb(241 245 249);font-size:.875rem;line-height:1.6}.ql-editor.ql-blank::before{color:rgb(100 116 139)!important;font-style:italic}
    </style>
</x-layouts.admin>
