<x-layouts.admin :admin-title="'Tournament Slots'">
    <div class="mx-auto max-w-6xl space-y-6">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div><a href="{{ route('admin.tournaments') }}" class="text-xs font-semibold text-indigo-300 hover:text-white">← Back to schedules</a><p class="mt-4 text-[10px] font-black uppercase tracking-[.25em] text-indigo-400">V2 tournament schedule</p><h1 class="mt-2 text-xl font-black text-white">{{ $template->name }}</h1><p class="mt-2 text-sm text-slate-400">Individual occurrences remain separate for brackets, money, and audit history.</p></div>
            <a href="{{ route('admin.tournaments.v2.templates.slots.create', $template) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Add slot</a>
        </div>
        <div class="rounded-xl border border-slate-800 bg-slate-900/60 p-4 text-sm text-slate-300"><span class="text-slate-500">Game:</span> {{ $template->game?->translations->first()?->name ?? $template->game?->slug }} <span class="mx-2 text-slate-700">•</span><span class="text-slate-500">Frequency:</span> {{ $template->recurrence_frequency?->value ?? 'one-time' }} <span class="mx-2 text-slate-700">•</span><span class="text-slate-500">Timezone:</span> {{ $template->timezone }}</div>
        <div class="overflow-hidden rounded-xl border border-slate-800 bg-[#0f172a]"><div class="overflow-x-auto"><table class="w-full text-left text-xs"><thead class="border-b border-slate-800 text-[10px] font-bold uppercase text-slate-500"><tr><th class="p-4">Slot</th><th class="p-4">Start</th><th class="p-4">Entry fee</th><th class="p-4">Teams</th><th class="p-4">Status</th><th class="p-4 text-right">Edit</th></tr></thead><tbody class="divide-y divide-slate-800/70">@forelse($template->scheduleSlots as $slot) @forelse($slot->occurrences as $occurrence) @php($statusLabel = in_array($occurrence->status->value, ['CANCELLED','REFUNDED'], true) ? 'Closed' : str_replace('_', ' ', $occurrence->status->value)) @php($isEditable = $occurrence->status->value === 'REGISTRATION_OPEN' && $occurrence->start_at?->isFuture() && request()->user()?->can('tournaments.manage')) @php($lockedMessage = $occurrence->status->value === 'ONGOING' ? 'This occurrence is ongoing and can no longer be updated.' : 'This occurrence has closed and can no longer be updated.')<tr><td class="p-4 text-slate-200">{{ $slot->label ?: 'Schedule slot' }}</td><td class="p-4 text-slate-400">{{ $occurrence->start_at?->timezone($occurrence->timezone)->format('M d, Y · g:i A') }}</td><td class="p-4 text-slate-300">${{ number_format((float) $occurrence->entry_fee, 2) }}</td><td class="p-4 text-slate-300">{{ $occurrence->registrations_count }}/{{ $occurrence->max_participants }}</td><td class="p-4"><span class="rounded border border-slate-700 bg-slate-900 px-2 py-1 text-[9px] font-black uppercase text-slate-300">{{ $statusLabel }}</span></td><td class="p-4 text-right">@if($isEditable)<a href="{{ route('admin.tournaments.v2.occurrences.edit', $occurrence) }}" class="inline-flex rounded-lg p-2 text-indigo-300 hover:bg-indigo-500/10 hover:text-white" title="Edit occurrence"><i data-lucide="pencil" class="h-4 w-4"></i><span class="sr-only">Edit occurrence</span></a>@else<span class="inline-flex" title="{{ $lockedMessage }}"><button type="button" disabled class="cursor-not-allowed rounded-lg p-2 text-slate-600"><i data-lucide="pencil" class="h-4 w-4"></i><span class="sr-only">Editing unavailable</span></button></span>@endif</td></tr>@empty @endforelse @empty <tr><td colspan="6" class="p-8 text-center text-slate-500">No schedule slots configured.</td></tr>@endforelse</tbody></table></div></div>
    </div>
</x-layouts.admin>
